= My Wiki
Paulo Jerônimo, {localdatetime}
:toc:
:numbered:
:icons: font
:experimental:

This repo contains the source code (master branch) of my wiki ( https://paulojeronimo.github.io/wiki ) published on (https://github.com/paulojeronimo/wiki/tree/gh-pages[gh-pages^] branch).

It uses https://tiddlywiki.com/[TiddlyWiki^] and is built with https://travis-ci.org/[Travis CI^] on each git commit.

The link:scripts/publish[publish script], configured in link:.travis.yml[], is called by Travis CI after wiki build (with `tiddlywiki` command) on each `commit` (and `push`) to this repo.

NOTE: if you want to configure something you'll need to copy the file link:scripts/config.sample[] to `scripts/config` and edit it as needed.

== Running this wiki locally

It may be a good idea to edit and see this wiki locally before publish it to GitHub Pages.

To do this, you need to install https://tiddlywiki.com/static/TiddlyWiki%2520on%2520Node.js.html[Tiddlywiki Node.js^] package (`npm install tiddlywiki`) and run the link:scripts/local[local script] as in the following command:

----
$ ./scripts/local start
----

Open the browser on http://localhost:8080 and edit the wiki.

To stop the TiddlyWiki execution just press kbd:[Ctrl+C].

== Running this wiki through Docker

You can also run this Wiki through Docker by executing the link:scripts/docker[docker script].

Building the TiddlyWiki container:

----
$ ./scripts/docker build
----

Starting TiddlyWiki:

----
$ ./scripts/docker start
----

Open the browser on http://localhost:8080 and edit the wiki.

Stopping TiddlyWiki:

----
$ ./scripts/docker stop
----

== Generating static files

All contents of this wiki can be statically generated by executing the link:scripts/static[static script].

== References

* https://github.com/danielo515/TW5-auto-publish2gh-pages/blob/master/README.md[danielo515/TW5-auto-publish2gh-pages README.md^].
* https://github.com/elasticdog/tiddlywiki-docker
