#!/usr/bin/env bash

[ "$BASE_DIR" ] || { echo "BASE_DIR not defined!"; exit 1; }

found=false
for cfg in config{,.sample}
do
  source "$BASE_DIR"/$cfg 2> /dev/null && { found=true; break; }
done
$found || echo "$cfg not found!"

[ "$TMPDIR" ] && {
  [ "${TMPDIR: -1}" = / ] && \
    log_dir=${TMPDIR%?}/wiki || \
    log_dir=$TMPDIR/wiki
} || log_dir=/tmp/wiki
mkdir -p $log_dir

log=$log_dir/`date +%s`.log
{
  echo "Log file: $log"
  echo "Date and time: `date`"
  echo "Configurations loaded from \"$cfg\" ..."
} | tee -a $log

list-tasks() {
  local tasks=$(sed -n 's/_\(.*\)() {/\1/p' $0 | tr '\n' '|')
  echo -n ${tasks%?}
}

tiddlywiki() {
  npx tiddlywiki "$@"
}

serve() {
  npx serve "$@"
}

main() {
  cd "$WIKI_BASE_DIR"
  [ "$1" ] && {
    task=_$1
    type "$task" &> /dev/null && {
      shift
      {
        echo "Running: $task $@"
        $task "$@" 2>&1
      } | tee -a $log
    }
  } || echo "$0 <`list-tasks`>"
}

# vim: set ts=2 sw=2 et:
