#!/usr/bin/env bash
DEBUG=${DEBUG:-false}
$DEBUG && set -x || set +x

BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

_build() {
  cd "$BASE_DIR"/..
  docker build --build-arg TIDDLYWIKI_VERSION=$TIDDLYWIKI_VERSION -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION .
}

_push() {
  docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION
}

_start() {
  docker run --detach --rm \
    --name tiddlywiki \
    --publish $WIKI_BIND:$WIKI_PORT:8080 \
    --mount "type=bind,source=${WIKI_BASE_DIR},target=/tiddlywiki" \
    $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION \
    $WIKI \
    --listen host=0.0.0.0
}

_stop() {
  docker stop tiddlywiki
}

_rmi() {
  docker rmi $DOCKER_IMAGE_NAME
}

main "$@"

# vim: set ts=2 sw=2 et:
