#!/usr/bin/env bash
DEBUG=${DEBUG:-false}
$DEBUG && set -x || set +x

BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

# If TiddlyWiki isn't installed, exit!
which tiddlywiki &> /dev/null || {
  [ "$1" != "install" ] && {
    echo "TiddlyWiki is not installed!"
    echo "Try run this: $0 install"
    exit 1
  }
}

cd "$WIKI_BASE_DIR"

install() {
  npm install -g tiddlywiki
}

start() {
  tiddlywiki $WIKI --listen host=$WIKI_BIND port=$WIKI_PORT
}

[ "$1" ] && {
  type "$1" > /dev/null && $1
} || echo "$0 <install|start>"

# vim: set ts=2 sw=2 et:
