#!/usr/bin/env bash
DEBUG=${DEBUG:-false}
$DEBUG && set -x || set +x

BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

check-tiddlywiki

_build() {
  # https://tiddlywiki.com/static/BuildCommand.html
  tiddlywiki $WIKI --build
}

_listen() {
  # https://tiddlywiki.com/static/ListenCommand.html
  tiddlywiki $WIKI --listen host=$WIKI_BIND port=$WIKI_PORT
}

_load() {
  # https://tiddlywiki.com/static/LoadCommand.html
  tiddlywiki $WIKI --load "$1"
}

_publish() {
  _build
  true || {
    local ghs=${!GH@}
    for gh in $ghs; do
      echo "$gh=${!gh}"
    done
  }
  "$BASE_DIR"/publish
}

main "$@"

# vim: set ts=2 sw=2 et:
