#!/usr/bin/env bash
set +x

BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

check-tiddlywiki
check-serve

_build() {
  tiddlywiki $WIKI --rendertiddlers [!is[system]] $:/core/templates/static.tiddler.html static text/plain
}

_clean() {
  rm -rf $WIKI/output
}

_serve() {
  local d=$WIKI/output/static
  [ -d $d ] && serve $d || echo "Directory \"$d\" does not exists!"
}

main "$@"

# vim: set ts=2 sw=2 et:
