#!/usr/bin/env bash
set +x

BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

build() {
  tiddlywiki $WIKI --rendertiddlers [!is[system]] $:/core/templates/static.tiddler.html static text/plain
}

clean() {
  rm -rf $WIKI/output
}

serve() {
  local d=$WIKI/output/static
  [ -d $d ] && http-server $d || echo "Directory \"$d\" does not exists!"
}

cd "$WIKI_BASE_DIR"
[ "$1" ] && {
  type "$1" > /dev/null && $1
} || echo "$0 <build|clean|serve>"
